part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const LOGIN = _Paths.LOGIN;
  static const NAVSCREEN = _Paths.NAVSCREEN;

  static const SIGNUPSCREEN = _Paths.SIGNUPSCREEN;

  static const EDITPROFILESCREEN = _Paths.EDITPROFILESCREEN;

  static const ENTRYLOGSCREEN = _Paths.ENTRYLOGSCREEN;
  static const HOMESCREEN = _Paths.HOMESCREEN;
  static const ALERTSSCREEN = _Paths.ALERTSSCREEN;
  static const MAINTANANCESCREEN = _Paths.MAINTANANCESCREEN;
  static const HISTORYSCREEN = _Paths.HISTORYSCREEN;
  static const STATUSSCREEN = _Paths.STATUSSCREEN;
  static const MANAGECOVERSSCREEN = _Paths.MANAGECOVERSSCREEN;
  static const NEWUSERSREQUESTSSCREEN = _Paths.NEWUSERSREQUESTSSCREEN;
  static const MANAGEUSERSSCREEN = _Paths.MANAGEUSERSSCREEN;
  static const EDITUSERSSCREEN = _Paths.EDITUSERSSCREEN;
  static const ADDUSERSSCREEN = _Paths.ADDUSERSSCREEN;
  static const SPLASHSCREEN = _Paths.SPLASHSCREEN;

  static const FORGETPASSWORDSCREEN = _Paths.FORGETPASSWORDSCREEN;
  static const REGISTERADMINSCREEN = _Paths.REGISTERADMINSCREEN;
  static const REGISTEREMPSCREEN = _Paths.REGISTEREMPSCREEN;
}

abstract class _Paths {
  static const LOGIN = '/LOGIN';
  static const NAVSCREEN = '/NAVSCREEN';

  static const SIGNUPSCREEN = '/SIGNUPSCREEN';

  static const EDITPROFILESCREEN = '/EDITPROFILESCREEN';
  static const ENTRYLOGSCREEN = '/ENTRYLOGSCREEN';
  static const HOMESCREEN = '/HOMESCREEN';
  static const ALERTSSCREEN = '/ALERTSSCREEN';
  static const MAINTANANCESCREEN = '/MAINTANANCESCREEN';
  static const HISTORYSCREEN = '/HISTORYSCREEN';
  static const STATUSSCREEN = '/STATUSSCREEN';
  static const MANAGECOVERSSCREEN = '/MANAGECOVERSSCREEN';
  static const NEWUSERSREQUESTSSCREEN = '/NEWUSERSREQUESTSSCREEN';
  static const MANAGEUSERSSCREEN = '/MANAGEUSERSSCREEN';
  static const EDITUSERSSCREEN = '/EDITUSERSSCREEN';
  static const ADDUSERSSCREEN = '/ADDUSERSSCREEN';
  static const SPLASHSCREEN = '/SPLASHSCREEN';

  static const FORGETPASSWORDSCREEN = '/FORGETPASSWORDSCREEN';
  static const REGISTERADMINSCREEN = '/REGISTERADMINSCREEN';
  static const REGISTEREMPSCREEN = '/REGISTEREMPSCREEN';
}
